### ISSUE TITLE
Can't include Invoiceable without implementing :refunded_at and :paid_at

### ISSUE THREAD

**Issue by LaurentVB** [commondream/payday#39]
Hello,

It is my understanding that I should be able to let my own Invoice model render as pdf using payday by adding ```include Payday::Invoiceable ```and implementing the ```bill_to``` and ```line_items```.
However, when I do that, it fails with a ```undefined local variable or method `refunded_at' for #<Invoice:0x007f863f2fee38>```error.

It looks like you're using ```defined?``` wrong in ```Invoiceable```
It should be 
```
def refunded?
  defined?(refunded_at) && !!refunded_at
end
```
(remove the colon in front of refunded_at to test for existence, otherwise ```defined?(:refunded_at)``` always returns "expression")

**Comment by ngelx** [comment]
+1
