### ISSUE TITLE
Sample application offline

### ISSUE THREAD

**Issue by byrnejb** [commondream/payday#44]
I went to the sample application href provided in the documentation and got this result:

    Application Error

    An error occurred in the application and your page could not be served. Please try again in a few
    moments.

    If you are the application owner, check your logs for details.

**Comment by commondream** [comment]
I went ahead and removed the link to the example app - Heroku shut down classic apps a while back and I'm pretty sure that's why it's gone now. I don't think it makes a ton of sense to update that.
